
Exercise 1 : Minimum and Maximum of Random Array
Instructions
Create a 5x5 array with random values and find the minimum and maximum values.

In [3]:
import numpy as np
np.random.seed(1)
array = np.random.randint(1, 100, (5,5))
print(f'mininum value : {np.min(array)}, maximum value : {np.max(array)}')

mininum value : 2, maximum value : 88


Exercise 2 : Matrix Normalization
Instructions
Normalize a 3x3 random matrix (subtract the mean and divide by the standard deviation of the matrix).

In [24]:
np.random.seed(1)
array =np.random.randint(1, 50, (3,3))
std = np.std(array)
avg = np.mean(array)
norm_array =((array -avg)/std).round(2)
print(f'array : {array :}')
print('')
print(f'''normalised array :
{norm_array}''')


array : [[38 44 13]
 [ 9 10 12]
 [ 6 16  1]]

normalised array :
[[ 1.56  2.   -0.26]
 [-0.55 -0.48 -0.33]
 [-0.77 -0.04 -1.13]]


Exercise 3 : Evenly Spaced Elements in Array
Instructions
Create a 1D array of 50 evenly spaced elements between 0 and 10, exclusive.

In [32]:
array =np.linspace(0, 10, 50)
array.round(2)

array([ 0.  ,  0.2 ,  0.41,  0.61,  0.82,  1.02,  1.22,  1.43,  1.63,
        1.84,  2.04,  2.24,  2.45,  2.65,  2.86,  3.06,  3.27,  3.47,
        3.67,  3.88,  4.08,  4.29,  4.49,  4.69,  4.9 ,  5.1 ,  5.31,
        5.51,  5.71,  5.92,  6.12,  6.33,  6.53,  6.73,  6.94,  7.14,
        7.35,  7.55,  7.76,  7.96,  8.16,  8.37,  8.57,  8.78,  8.98,
        9.18,  9.39,  9.59,  9.8 , 10.  ])

Exercise 4 : Matrix Multiplication
Instructions
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

Expected Output:

In [36]:
np.random.seed(1)
array1 = np.random.randint(1, 30, size=(5,3))
array2 =np.random.randint(1, 90,size=(3,2))
product = array1 @ array2
product

array([[ 901, 1513],
       [ 801, 1464],
       [ 877,  577],
       [ 468, 1589],
       [1321, 2967]], dtype=int32)

Exercise 5
Instructions
Utilize your understanding of matrix multiplication to solve this exercise.
Create two matrices of compatible dimensions.
Perform matrix multiplication on these matrices and display the result.
Ensure the dimensions of the matrices allow for valid multiplication.
Tip: Remember that the number of columns in the first matrix should match the number of rows in the second matrix for successful multiplication.





In [37]:
np.random.seed(1)
array_1 =np.random.randint(0, 30, (4, 2))
array_2 = np.random.randint(0,20,(2,5))
array_1 @ array_2

array([[143, 146, 203, 115, 233],
       [104, 240, 156, 184, 228],
       [143, 210, 207, 163, 261],
       [195, 170, 275, 135, 305]], dtype=int32)