🌟 Exercise 1 : Array Creation and Manipulation

Create a 1D NumPy array containing numbers from 0 to 9.

In [47]:
import numpy as np
id= np.arange(10)
id

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


🌟 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [48]:
array = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
array 

array([3, 2, 0, 1, 2])

 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.



In [49]:
array =np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

exercise 4:Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [50]:
np.random.seed(1)
array =np.random.default_rng().integers(21,size=(4,5))
array

array([[18,  9, 18,  9,  6],
       [ 3,  8,  9,  3, 12],
       [19,  6, 20,  1,  9],
       [19, 20, 16,  5,  9]])


🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])


In [51]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
row2 =array[1]
row2

array([20, 21, 22, 23, 24])

 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [52]:
array = np.arange(10)
inv_array =array[::-1]
inv_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

In [53]:
array = np.arange(16).reshape(4,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5


In [54]:
array = np.arange(1, 20, 2)
print(f'Sum:{np.sum(array)}, Average: { np.mean(array)}')

Sum:100, Average: 10.0


 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [55]:
array = np.arange(1,21).reshape(4,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

In [56]:
array =np.arange(10)
odd = array[array%2 !=0]
odd

array([1, 3, 5, 7, 9])